config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3webapp:
      branch: main
      repo: https://github.com/EOSC-synergy/o3webapp
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3webapp git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chocolate-beaver.sh
        container: qc.acc_chummy-mauve-axolotl
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3webapp find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-plum-bombay.sh
        container: qc.doc_silly-emerald-dragon
      github.com/EOSC-synergy/o3webapp git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-eggplant-walrus.sh
        container: qc.doc_skinny-gold-schnauzer
      github.com/EOSC-synergy/o3webapp markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-wisteria-tiger.sh
        container: qc.doc_jumpy-orchid-butterfly
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3webapp licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-turquoise-barnacle.sh
        container: qc.lic_snoopy-charcoal-skunk
  QC.Met:
    repos:
      github.com/EOSC-synergy/o3webapp validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-sangria-hound.sh
        container: qc.met_flabby-olive-ray
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3webapp hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-pink-chow.sh
        container: qc.sty_gimpy-wisteria-emu
      github.com/EOSC-synergy/o3webapp jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-salmon-ostrich.sh
        container: qc.sty_muggy-maroon-millipede
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3webapp get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-myrtle-hornet.sh
        container: qc.ver_nerdy-razzmatazz-reindeer
timeout: 5400
